name: Build Geode Mod

on:
  push:
    branches: ["**"]
  workflow_dispatch:

jobs:
  build:
    name: Build Mod
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build Android
        uses: geode-sdk/build-geode-mod@main
        with:
          target: Android64
          setup-android: true
        env:
          GEODE_SDK: ${{ github.workspace }}/geode-sdk
